package com.acs560.ShareTaxi.entities;

import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * The CarEntity class represents a car in the ShareTaxi system.
 * It is mapped to the "cars" table in the database and stores
 * information about the car's owner, model, license plate, 
 * available seats, mileage, color, and car type.
 */
@Entity
@Table(name = "cars")
public class CarEntity {

    /**
     * Unique identifier for the car.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who owns the car.
     * This is a foreign key reference to the CustomUserEntity table.
     */
    @ManyToOne
    @JoinColumn(name = "owner_id", nullable = false)
    private CustomUserEntity owner;

    /**
     * The model or make of the car (e.g., Toyota Prius).
     */
    private String model;

    /**
     * The car's license plate number, which must be unique.
     */
    @Column(length = 20)
    private String licensePlate;

    /**
     * The number of seats available in the car for passengers.
     */
    private int seatsAvailable;

    /**
     * The car's mileage, stored as a decimal value.
     */
    @Column(precision = 8, scale = 2)
    private BigDecimal mileage;

    /**
     * The color of the car.
     */
    @Column(length = 50)
    private String color;

    /**
     * The type of the car (e.g., sedan, SUV, hatchback).
     */
    @Column(length = 50)
    private String carType;

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CustomUserEntity getOwner() {
        return owner;
    }

    public void setOwner(CustomUserEntity owner) {
        this.owner = owner;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getLicensePlate() {
        return licensePlate;
    }

    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }

    public int getSeatsAvailable() {
        return seatsAvailable;
    }

    public void setSeatsAvailable(int seatsAvailable) {
        this.seatsAvailable = seatsAvailable;
    }

    public BigDecimal getMileage() {
        return mileage;
    }

    public void setMileage(BigDecimal mileage) {
        this.mileage = mileage;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getCarType() {
        return carType;
    }

    public void setCarType(String carType) {
        this.carType = carType;
    }

    /**
     * Returns a string representation of the car, including the model and license plate.
     *
     * @return a string in the format "model (licensePlate)"
     */
    @Override
    public String toString() {
        return model + " (" + licensePlate + ")";
    }
}
