package com.acs560.ShareTaxi.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * The RideRequestEntity class represents a request made by a user to join a specific ride
 * in the ShareTaxi system. It is mapped to the "ride_requests" table in the database and
 * contains details about the requested ride, the user making the request, the status of the 
 * request, the number of seats requested, and any additional comments.
 */
@Entity
@Table(name = "ride_requests")
@Getter
@Setter
@ToString
public class RideRequestEntity {

    /**
     * Unique identifier for the ride request.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The ride being requested.
     * This is a foreign key reference to the RideEntity table.
     */
    @ManyToOne
    @JoinColumn(name = "ride_id", nullable = false)
    private RideEntity ride;

    /**
     * The user making the ride request.
     * This is a foreign key reference to the CustomUserEntity table.
     */
    @ManyToOne
    @JoinColumn(name = "requested_by", nullable = false)
    private CustomUserEntity requestedBy;

    /**
     * The current status of the request (e.g., "Pending", "Approved", "Rejected").
     */
    @Column(length = 50)
    private String requestStatus;

    /**
     * The number of seats requested by the user.
     * Defaults to 1 if not specified.
     */
    private int seatsRequested = 1;

    /**
     * Any additional comments provided by the user when requesting the ride.
     */
    @Column(length = 255)
    private String comments;
}
